#Gallery
gallery:
  - title: Weddings
    imgurl: weddings
    images: [image1, image2, image3, image5, image6]
    
  - title: Parties &amp; Celebrations
    imgurl: parties
    images: [image2, image3, image4, image5, image6, image7]
    
  - title: Kids
    imgurl: kids  
    images: [image1, image2, image3, image4, image5, image6, image7, image8, image9, image10, image11, image12]          
    
 