#Testimonials -------------
testimonials:
  - name: 'Khadijah Sesay'
    quote: 'These ladies are very professional, have great time management & are able to work under pressure. I loved how they understood my vision and had the venue looking amazing for my launch party. Keep up the good work, I will definitely be using your services again.'
    
  - name: Di'Jah Diallo
    quote: 'Would highly recommend these beautiful ladies so professional the kids really enjoyed themselves you guys made the party so enjoyable the decorations was outstanding thank you soooooo much.'
    
  - name: 'Amanda Palmer - Meeting Coordinator'
    quote: 'you did a fabulous job with the decorations. We received nothing but good comments. I would certainly not hesitate recommending you to anyone. We are already talking about next year…hopefully, you will be available.'
    
  - name: 'Fatima - Mother of the bride'
    quote: "Thank you so much for adding a colourful touch to my daughter's wedding. It was more than what we expected. It was magical and breathtaking."
    
         
    
          
    
 